### ISSUE TITLE
Function parameters hidden

### ISSUE THREAD

**Issue by srfrnk** [redhat-developer/vscode-java#912]
VSCode Info:
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic
```
```
Extension | Author (truncated) | Version
-- | -- | --
lua-debug | act | 1.0.3
project-manager | ale | 10.5.1
makeRunner | ale | 0.1.2
ignoregit | And | 1.0.1
ng-template | Ang | 0.1.11
vscode-groovy | Arg | 0.0.1
solidity-extended | bea | 3.0.2
git-easy | bib | 1.11.0
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
jsrefactor | cms | 2.18.2
gitignore | cod | 0.6.0
bracket-pair-colorizer | Coe | 1.0.61
scala | dal | 0.0.5
vscode-markdownlint | Dav | 0.26.0
jshint | dba | 0.10.20
vscode-eslint | dba | 1.8.2
vscode-quick-select | dba | 0.2.8
java-decompiler | dgi | 0.0.2
dlang | dla | 0.10.0
git-extension-pack | don | 0.1.3
githistory | don | 0.4.6
jupyter | don | 1.1.5
xml | Dot | 2.4.0
scala-lsp | dra | 0.2.3
gitlens | eam | 9.6.3
vscode-html-css | ecm | 0.2.0
EditorConfig | Edi | 0.13.0
tslint | eg2 | 1.0.43
vscode-npm-script | eg2 | 0.3.5
LogFileHighlighter | emi | 2.4.3
json-tools | eri | 1.0.2
vscode-toggle-column-selection | eri | 1.0.4
prettier-vscode | esb | 1.9.0
git-project-manager | fel | 1.7.1
vscode-npm | fkn | 3.3.0
code-runner | for | 0.9.8
vscode-mysql | for | 0.4.0
macros | ged | 1.2.1
vscode-javac | geo | 0.2.18
gitignore-templates | has | 1.0.1
jsonnet | hep | 0.1.0
vscode-ungit | Hir | 2.0.0
beautify | Hoo | 1.4.11
githd | hui | 2.1.0
Scala | itr | 0.1.7
mysql-syntax | jak | 1.3.1
search-node-modules | jas | 1.3.0
angular-essentials | joh | 0.6.1
Angular2 | joh | 7.1.4
vscode-peacock | joh | 2.1.1
solidity | Jua | 0.0.53
Lua | key | 0.0.9
vscode-github | Kni | 0.30.2
refactorix | kri | 0.3.6
cql | Law | 0.8.7
expand-region | let | 0.1.2
vsls-whiteboard | los | 0.0.8
autoconf | mae | 0.0.9
MagicPython | mag | 1.1.0
ninja-syntax | mel | 1.0.0
gitignore | mic | 1.0.1
vs-script-commands | mkl | 8.0.0
vscode-kubernetes-tools | ms- | 0.1.18
python | ms- | 2019.4.12954
azure-account | ms- | 0.8.2
cpptools | ms- | 0.22.1
vsliveshare | ms- | 1.0.125
vsliveshare-audio | ms- | 0.1.50
debugger-for-chrome | msj | 4.11.3
angular2-inline | nat | 0.0.17
integrated-terminal-tasks | ntc | 1.1.0
vscode-docker | Pet | 0.6.1
material-icon-theme | PKi | 3.7.0
java | red | 0.44.0
vscode-yaml | red | 0.4.0
bash-debug | rog | 0.3.4
shebang-snippets | rpi | 0.1.3
rust | rus | 0.6.1
annotator | ryu | 1.0.0
markdown-preview-enhanced | shd | 0.3.13
incremental-search | sie | 0.2.1
vscode-zipexplorer | sle | 0.3.1
java-generate-setters-getters | soh | 4.2.1
user-extensions | srf | 1.0.3
code-spell-checker | str | 1.7.6
ignore-gitignore | stu | 1.0.1
python | tht | 0.2.3
pdf | tom | 0.5.0
vscodeintellicode | Vis | 1.1.5
vscode-java-debug | vsc | 0.18.0
vscode-java-dependency | vsc | 0.4.0
vscode-java-pack | vsc | 0.7.1
vscode-java-test | vsc | 0.16.0
vscode-maven | vsc | 0.16.2
nodejs-extension-pack | wad | 0.1.9
JavaScriptSnippets | xab | 1.7.2
markdown-pdf | yza | 1.2.0
vscode-open-in-github | ziy | 1.3.6
```
System Info:
```
CPUs | Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2704)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwaresurface_synchronization: enabled_onvideo_decode: unavailable_offwebgl: enabledwebgl2: enabled
Load (avg) | 0, 1, 1
Memory (System) | 31.32GB (2.39GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%
```

Steps to Reproduce:

1. Open a **Java** project
1. Open a Java file.
1. Move cursor to a class constructor or function call.
1. Press (Ctrl+Space in linux)
1. Popup width is too small and parameter list is hidden.

See below:
![bug](https://user-images.githubusercontent.com/1501654/57140276-0bc32e80-6dc0-11e9-9259-b7a00e17bba7.png)

**Comment by fbricon** [comment]
Closing as duplicate of https://github.com/redhat-developer/vscode-java/issues/249. Long story short, vscode needs to fix https://github.com/Microsoft/vscode/issues/29757

**Comment by srfrnk** [comment]
So I went ahead and looked into Microsoft/vscode#29757.

Looks like until this is fixed a workaround can be made: https://github.com/srfrnk/vscode/commit/8ab1ef2464e14e467c3fba3e914f8e54c4df3c43

So for anyone wanting to do that:
# 1
Open `/<VSCODE INSTALL DIR>/resources/app/out/vs/workbench/workbench.main.css` (my ubuntu system has it in `usr/share/code`)
# 2
Find
```css
.monaco-editor .suggest-widget>.details,
.monaco-editor .suggest-widget>.message,
.monaco-editor .suggest-widget>.tree {
    border-style: solid;
    border-width: 1px;
    box-sizing: border-box;
}
```
# 3
Add `overflow: auto;`
Should look like this:
```css
.monaco-editor .suggest-widget>.details,
.monaco-editor .suggest-widget>.message,
.monaco-editor .suggest-widget>.tree {
    border-style: solid;
    border-width: 1px;
    box-sizing: border-box;
    overflow: auto;
}
```
# 4
Find
```css
.monaco-editor .suggest-widget .monaco-list {
    -webkit-user-select: none;
    -moz-user-select: -moz-none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}
```
# 5
Add `width: 1500px;`
Should like like this:
```css
.monaco-editor .suggest-widget .monaco-list {
    -webkit-user-select: none;
    -moz-user-select: -moz-none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
    width: 1500px;
}
```
# 6
Reload VSCode
